runtime: python39

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  CLOUD_STORAGE_BUCKET_NAME: stldigital-openai-bucket

handlers:


- url: /
  static_files: /index.html
  upload: /index.html
